"""Render state into ``dashboard.md`` — the read-only view.

Triggered automatically after every state write (see :func:`rebuild`).
Design doc §5.5 reserves the option to debounce later; for now we just
rebuild synchronously and keep the renderer simple.
"""
from __future__ import annotations

from pathlib import Path

from . import heartbeat
from . import state as state_mod
from .events import read_events, utcnow_iso
from .locking import atomic_write

RECENT_EVENTS_DISPLAYED = 10


def _task_agent(task: dict) -> str:
    """Return the agent string for a task, reading from stages if needed."""
    if "agent" in task:
        return str(task["agent"])
    stages = task.get("stages") or []
    if not stages:
        return "-"
    current = task.get("current_stage", 0)
    if isinstance(current, int) and 0 <= current < len(stages):
        return str(stages[current].get("agent", "-"))
    return str(stages[0].get("agent", "-"))


def render(state_dir: Path) -> str:
    project = state_mod.load_project(state_dir)
    tasks = state_mod.list_tasks(state_dir)
    events = read_events(state_dir / "events.jsonl")
    last_seen = heartbeat.last_per_task(events)

    name = project.get("name", "?")
    workspace = project.get("workspace") or "worktree"

    lines: list[str] = []
    lines.append(f"# fleet — {name}")
    lines.append("")
    lines.append("_Auto-generated by `fleet`. Do not edit by hand._  ")
    lines.append(f"_Updated: {utcnow_iso()}_")
    lines.append("")
    lines.append(f"- project name: **{name}**")
    lines.append(f"- created: `{project.get('created_at', '?')}`")
    lines.append(f"- fleet version: `{project.get('version', '?')}`")
    lines.append(f"- workspace: `{workspace}`")
    lines.append("")

    # Highlight tasks awaiting orders.
    awaiting_orders = [t for t in tasks if t.get("status") == "awaiting_orders"]
    if awaiting_orders:
        lines.append("## ⚠ Awaiting orders")
        lines.append("")
        for t in awaiting_orders:
            tid = t.get("id", "?")
            lines.append(
                f"- **task-{tid}** — {t.get('title', '-')} "
                f"(agent: `{_task_agent(t)}`)"
            )
        lines.append("")

    # Full task table.
    lines.append("## Tasks")
    lines.append("")
    if not tasks:
        lines.append("_(no tasks yet)_")
    else:
        lines.append("| ID | Title | Status | Agent | Workspace | Last seen |")
        lines.append("|----|-------|--------|-------|-----------|-----------|")
        for t in tasks:
            tid = t.get("id", "?")
            lines.append(
                "| {id} | {title} | {status} | {agent} | {workspace} | {seen} |".format(
                    id=tid,
                    title=t.get("title", "-"),
                    status=t.get("status", "-"),
                    agent=_task_agent(t),
                    workspace=t.get("workspace", "-"),
                    seen=last_seen.get(tid, "—"),
                )
            )
    lines.append("")

    # Recent event tail.
    lines.append(f"## Recent events (last {RECENT_EVENTS_DISPLAYED})")
    lines.append("")
    if not events:
        lines.append("_(none)_")
    else:
        for ev in events[-RECENT_EVENTS_DISPLAYED:]:
            tid = ev.get("task_id", "—")
            lines.append(
                f"- `{ev.get('ts', '?')}`  **{ev.get('type', '?')}**  task-{tid}"
            )
    lines.append("")
    return "\n".join(lines) + "\n"


def rebuild(state_dir: Path) -> Path:
    """Re-render dashboard.md from current state. Returns the dashboard path."""
    out = state_dir / "dashboard.md"
    text = render(state_dir)
    with atomic_write(out) as f:
        f.write(text)
    return out
